/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topic_5_sql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import topic_5_sql.Controller.Persistence.OperationDB;
import topic_5_sql.Controller.Persistence.ConnectionDB;

/**
 *
 * @author Frederic
 */
public class FrameResult extends javax.swing.JFrame {

    private ConnectionDB conn;
    private Object[][] result = null;
    private OperationDB operation = null;

    /**
     * Creates new form FrameResult
     */
    public FrameResult() {
        initComponents();
        operation = new OperationDB();
        conn = new ConnectionDB();

    }

    /**
     * Using a schem of persistence to enter to the data base. This method is
     * called from the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        txt_course = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_list = new javax.swing.JButton();
        btn_note_final = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_last_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_number = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jLabel1.setText("Listar por Curso");

        btn_list.setText("Listar");
        btn_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActionPerformed(evt);
            }
        });

        btn_note_final.setText("List for Note");
        btn_note_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_note_finalActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name:");

        jLabel3.setText("Registrantion number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_course, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_list, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_note_final, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_last_name)
                            .addComponent(txt_number))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_list)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btn_note_final)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActionPerformed
        String where = "";
        StringBuilder res = new StringBuilder();
        String name = txt_course.getText();
        String orderby = "  STUDENT.last_name  ";
        String fields = " COURSE.name,TEACHER.last_name,TEACHER.first_name,STUDENT.last_name,STUDENT.first_name ";
        String error="Nothing in the DataBase";
        //notacion SQL1
        String tabla = " TEACHER,STUDENT ,STUDENTXCOURSEXNOTA ,COURSE ,TEACHERXCOURSE ";

        if (name.compareTo("") != 0) {

            where += " COURSE.name LIKE '" + name + "%' and";

        }
        //I should use Alias for the table 
        where += "      TEACHER.id_teacher=TEACHERXCOURSE.id_teacher ";
        where += " and TEACHERXCOURSE.id_course=COURSE.id_course ";
        where += " and  STUDENTXCOURSEXNOTA.id_student=STUDENT.id_registration ";
        where += " and STUDENTXCOURSEXNOTA.id_course=COURSE.id_course ";
        try {

            result = operation.select(tabla, fields, where, orderby, conn.accessBD());

            if (result != null) {
                for (int i = 0; i < result.length; i++) {

                    res.append("Course:" + result[i][0].toString() + "\n");
                    res.append("Teacher:" + result[i][1].toString() + "," + result[i][2].toString() + "\n");
                    res.append("Student:" + result[i][3].toString() + "," + result[i][4].toString() + "\n");

                }

                this.txt_area.setText(res.toString());
            }
            conn.closeCon();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, error);
        } finally {
            conn.closeCon();
        }


    }//GEN-LAST:event_btn_listActionPerformed

    private void btn_note_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_note_finalActionPerformed
        String where = " ";
        String number = this.txt_number.getText().trim();
        String apellido = this.txt_last_name.getText().trim();
        StringBuilder res = new StringBuilder();
        String tabla = " StudentXCourseXNota,Student,Course ";
        String orderby = "  StudentXCourseXNota.note_final,Course.name  ";
        String fields = " StudentXCourseXNota.note_final ";
            String error="The note are all in null";
        if (apellido.compareTo("") != 0) {

            where += "  Student.last_name LIKE '" + apellido + "%' and";

            if (number.compareTo("") != 0) {

                where += "  Student.id_registration=" + number + " and";
            }
        } else {
            if (number.compareTo("") != 0) {
                where += " Student.id_registration=" + number + " and";
            }
        }

        where += " StudentXCourseXNota.id_student=Student.id_registration and";
        where += "  StudentXCourseXNota.id_course=Course.id_course ";

        try {

            result = operation.select(tabla, fields, where, orderby, conn.accessBD());

            if (result != null) {
                for (int i = 0; i < result.length; i++) {
                    res.append(result[i].toString() + "\n");

                }

                this.txt_area.setText(res.toString());
            }
            conn.closeCon();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, error);
        } finally {
            conn.closeCon();
        }


    }//GEN-LAST:event_btn_note_finalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_note_final;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_course;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_number;
    // End of variables declaration//GEN-END:variables
}
